[package]
name = "hntc"
description = "(Useless) HN Terminal Client"
version = "0.1.0"

authors = ["Giulio Russo <me@giuuliorusso.me>"]
license = "MIT"

edition = "2018"

[dependencies]
chrono = "0.4.19"
crossterm = "0.18.0"
futures = "0.3.5"
open = "1.4.0"
reqwest = { version = "0.10.8", features = ["json"] }
serde = { version = "1.0.116", features = ["derive"] }
structopt = "0.3.18"
tokio = { version = "0.2.22", features = ["full"] }
tui = { version = "0.12.0", features = ["crossterm"], default-features = false }
