[package]
name = "hntc"
description = "(Useless) HN Terminal Client"
version = "0.1.0"

authors = ["Giulio Russo <me@giuuliorusso.me>"]
license = "MIT"

edition = "2018"

[dependencies]
chrono = "0.4.19"
crossterm = "0.18.2"
futures = "0.3.8"
open = "1.4.0"
reqwest = { version = "0.10.9", features = ["json"] }
serde = { version = "1.0.118", features = ["derive"] }
structopt = "0.3.21"
tokio = { version = "0.2.24", features = ["full"] }
tui = { version = "0.13.0", features = ["crossterm"], default-features = false }
