[package]
name = "hntc"
description = "(Useless) HN Terminal Client"
version = "0.1.0"

authors = ["Giulio Russo <me@giuuliorusso.me>"]
license = "MIT"

edition = "2018"

[dependencies]
chrono = "0.4.19"
crossterm = "0.21.0"
futures = "0.3.17"
open = "2.0.1"
reqwest = { version = "0.10.10", features = ["json"] }
serde = { version = "1.0.127", features = ["derive"] }
structopt = "0.3.23"
tokio = { version = "0.2.25", features = ["full"] }
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }
