name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        run: sudo apt install libssl-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
